declare module 'lucide-react';
declare module 'firebase/firestore';
declare module 'firebase/app';
declare module 'firebase/auth';
declare module 'firebase/app-check';
declare module 'lottie-react';
declare module 'recharts';
declare module 'react-markdown';
declare module 'remark-gfm';
